project: 
  type: website

website: 
  page-navigation: true
  title: "NOAA quarto simple" 
  site-url: "https://e-perl-NOAA.github.io/NOAA-quarto-simple/"
  repo-url: "https://github.com/e-perl-NOAA/NOAA-quarto-simple"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://raw.githubusercontent.com/nmfs-opensci/assets/main/logo/nmfs-opensci-logo3.png"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        https://e-perl-NOAA.github.io/NOAA-quarto-simple/"
        "Link to Website"
      - icon: github
        https://github.com/e-perl-NOAA/NOAA-quarto-simple"
        "Link to GitHub"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/add-content.qmd
        text: Add content
      - href: content/customizing.qmd
        text: Customizing
      - href: content/rendering.qmd
        text: Rendering
      - href: content/rmarkdown.Rmd
        text: R Markdown files
      - href: content/code.qmd
        text: Code in your files
      - href: content/acknowledgements.qmd
        text: Acknowledgements

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
