on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Render and Publish

env:
  PAGES_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
  REPO_URL: https://github.com/${{ github.repository }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get repo name and github.io name
        run: |
          echo "${{ env.PAGES_URL }}"
          echo "${{ env.REPO_URL }}"
          
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up R (needed for Rmd)
        uses: r-lib/actions/setup-r@v2

      # If you need other R packages, add them here
      - name: Install packages (needed for Rmd)
        run: Rscript -e 'install.packages(c("rmarkdown", "knitr", "jsonlite"))'
          
      - name: Edit quarto.yml with correct repo name and github.io site
        # if: github.event.head_commit.id == github.event.repository.created_at
        id: change-repo-name
        run: |
          quarto_yml <- readLines("_quarto.yml", encoding = "UTF-8")
          quarto_yml[7] <- gsub("https://.*", paste0(Sys.getenv('PAGES_URL'), '"'), quarto_yml[7])
          quarto_yml[8] <- gsub("https://.*", paste0(Sys.getenv('REPO_URL'), '"'), quarto_yml[8])
          quarto_yml[24] <- gsub("href: .*", paste0(Sys.getenv('PAGES_URL'), '"'), quarto_yml[24])
          quarto_yml[25] <- gsub('text: .*', paste0('"Link to Website"'), quarto_yml[25])
          quarto_yml[27] <- gsub("href: .*", paste0(Sys.getenv('REPO_URL'), '"'), quarto_yml[27])
          quarto_yml[28] <- gsub('text: .*', paste0('"Link to GitHub"'), quarto_yml[28])
          writeLines(quarto_yml, "_quarto.yml")
        shell: Rscript {0}
       
      - name: Commit changes to _quarto.yml
        # if: github.event.head_commit.id == github.event.repository.created_at
        uses: EndBug/add-and-commit@v9
        with: 
          add: './_quarto.yml'
          message: 'update _quarto.yml with site and github.io name'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: false
          # uncomment below and fill to pin a version
          # version: 0.9.600

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
