on:
  create:
  push:
  fork:
  workflow_dispatch:

name: Render and Publish

env:
  PAGES_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
  REPOSITORY_URL: https://github.com/${{ github.repository_owner }}/${{ github.repository }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get repo name and github.io name
        run: |
          echo "${{ env.PAGES_URL }}"
          echo "${{ env.REPO_URL }}"
          
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up R (needed for Rmd)
        uses: r-lib/actions/setup-r@v2

      - name: Install packages (needed for Rmd)
        run: Rscript -e 'install.packages(c("rmarkdown", "knitr", "jsonlite"))'
          
      - name: Edit quarto.yml with correct repo name and github.io site
        id: change-repo-name
        run: |
          quarto_yml <- readLines("_quarto.yml", encoding = "UTF-8")
          quarto_yml[7] <- gsub("https://.*", paste0(Sys.getenv('PAGES_URL'), '"'), quarto_yml[7])
          quarto_yml[7]
          quarto_yml[8] <- gsub("https://.*", paste0('https://github.com/', Sys.getenv('REPO_URL'), '"'), quarto_yml[8])
          quarto_yml[8]
          writeLines(quarto_yml, "_quarto.yml")
          cat('io_changed=', 'TRUE', sep='', file=Sys.getenv('GITHUB_OUTPUT'), append=TRUE)
        shell: Rscript {0}
       # if: ${{ github.event.repository.fork }}
       
      - name: Commit changes to _quarto.yml
        uses: EndBug/add-and-commit@v9
        with: 
          add: './_quarto.yml'
          message: 'update _quarto.yml with site and github.io name'
        #if: ${{ steps.change-repo-name.outputs.io_changed }}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: false
          # uncomment below and fill to pin a version
          # version: 0.9.600
      
      # add software dependencies here

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
